### ISSUE TITLE
Pre-PR: webhook creation support

### ISSUE THREAD

**Issue by cpick** [uw-labs/go-onfido#11]
I've [been working on](https://github.com/cpick/go-onfido/tree/webhook) expanding webhook support.  That branch has `CreateWebhook` and `ListWebhooks` which are already functional.
If this looks like it would be useful in the main project I'd be happy to open a PR.

(I'm not completely happy withe the `WebhookRef` type name that I've been using and would very much appreciate any alternative suggestions.)

**Comment by MarkSonghurst** [comment]
@cpick Many thanks for your work, I need to list webhooks so I copied your diff into my own fork and also added unit tests.
I might some minor changes to suit my Go coding style, such as creating a new source file for your code.
I've since abandoned making PRs into this parent fork, but if you want my changes you can find them here:
https://github.com/MarkSonghurst/go-onfido/blob/webhook/webhookref.go
https://github.com/MarkSonghurst/go-onfido/blob/webhook/webhookref_test.go

Thanks again, you saved me a days work :-)

**Comment by SpeedyCoder** [comment]
@cpick this looks good, we would be happy to add it to this repo. I can't think of any better name than `WebhookRef `. Though I would prefer to have things in separate files like @MarkSonghurst did on his branch, as interacting with the webhook api and parsing webhook calls are two quite different things.

Sorry for being super slow to respond, I was busy with other stuff and forgot about the PRs and issues on this repo 😅 I have now cleaned up most of the pending PRs and I will try to be more responsive from now on.

**Comment by MarkSonghurst** [comment]
@cpick If you want I can submit my files as a PR. It's your code though so I don't want to take the glory ;-)

**Comment by cpick** [comment]
@MarkSonghurst that would be great, please do!

**Comment by SpeedyCoder** [comment]
This was added in https://github.com/uw-labs/go-onfido/pull/25
